// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://arkhqgswgsuprnrspygu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFya2hxZ3N3Z3N1cHJucnNweWd1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyMTQwMjYsImV4cCI6MjA3Mzc5MDAyNn0.Fgfx8DtD1HvZSjeC4ii0AMTuUZMhVHqphGfJTldAEKM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});